class EmergencyAction {
  final String name;
  final String icon;
  final String category;
  final List<String> steps;
  EmergencyAction({required this.name, required this.icon, required this.category, required this.steps});
}

final List<EmergencyAction> emergencyActions = [
  EmergencyAction(name:'Heart Attack',icon:'❤️',category:'Cardiac',steps:['Call 108 immediately','Chew 1 aspirin (300mg) if not allergic','Sit upright, loosen clothing','Stay calm, breathe slowly','If unconscious, begin CPR']),
  EmergencyAction(name:'Choking',icon:'😰',category:'Airway',steps:['Ask "Are you choking?"','Stand behind, wrap arms around waist','Make a fist above navel','Give 5 quick upward abdominal thrusts','Repeat until object is expelled or person becomes unconscious']),
  EmergencyAction(name:'Stroke',icon:'🧠',category:'Cardiac',steps:['Remember FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 108','Note the time symptoms started','Keep person lying with head elevated','Do NOT give food or water','Stay with them until help arrives']),
  EmergencyAction(name:'Severe Bleeding',icon:'🩸',category:'Trauma',steps:['Apply firm pressure with clean cloth','Elevate injured area above heart','Do NOT remove embedded objects','Apply tourniquet only as last resort','Call 108 if bleeding won\'t stop']),
  EmergencyAction(name:'Burns',icon:'🔥',category:'Trauma',steps:['Cool burn under running water 10-20 min','Remove jewelry near burn','Cover loosely with sterile gauze','Do NOT apply ice, butter or toothpaste','Seek help for burns larger than palm']),
  EmergencyAction(name:'Fracture',icon:'🦴',category:'Trauma',steps:['Immobilize the area - don\'t realign','Apply ice wrapped in cloth','Elevate if possible','Use splint or sling for support','Go to emergency room']),
  EmergencyAction(name:'Seizure',icon:'⚡',category:'Neurological',steps:['Clear area of dangerous objects','Place person on their side','Cushion their head','Do NOT restrain or put anything in mouth','Time the seizure, call 108 if >5 min']),
  EmergencyAction(name:'Allergic Reaction',icon:'🤧',category:'Allergic',steps:['Use EpiPen if available (inject into outer thigh)','Call 108 immediately','Lay person flat, elevate legs','Loosen tight clothing','Give antihistamine if can swallow']),
  EmergencyAction(name:'Drowning',icon:'🌊',category:'Airway',steps:['Remove from water safely','Call 108','Check breathing, begin CPR if needed','Place in recovery position if breathing','Keep warm with blankets']),
  EmergencyAction(name:'Electric Shock',icon:'⚡',category:'Trauma',steps:['Do NOT touch person if still in contact','Turn off power source','Call 108','Check breathing, begin CPR if needed','Treat burns and keep warm']),
  EmergencyAction(name:'Poisoning',icon:'☠️',category:'Toxic',steps:['Call Poison Control','Identify the substance if possible','Do NOT induce vomiting unless told to','Save container/sample of poison','Monitor breathing and consciousness']),
  EmergencyAction(name:'Snake Bite',icon:'🐍',category:'Bites',steps:['Keep still, stay calm','Remove jewelry near bite','Keep bite below heart level','Do NOT suck venom or apply tourniquet','Get to hospital immediately']),
  EmergencyAction(name:'Dog Bite',icon:'🐕',category:'Bites',steps:['Wash wound with soap and water 5 min','Apply antiseptic','Cover with sterile bandage','Get tetanus shot if needed','Report to animal control']),
  EmergencyAction(name:'Bee Sting',icon:'🐝',category:'Bites',steps:['Remove stinger by scraping sideways','Wash area with soap and water','Apply ice pack','Take antihistamine for swelling','Watch for allergic reaction signs']),
  EmergencyAction(name:'Heat Stroke',icon:'🌡️',category:'Environmental',steps:['Move to cool area immediately','Remove excess clothing','Cool with water/ice on neck, armpits, groin','Fan the person','Call 108 - this is life-threatening']),
  EmergencyAction(name:'Hypothermia',icon:'🥶',category:'Environmental',steps:['Move to warm shelter','Remove wet clothing','Wrap in warm blankets','Give warm (not hot) drinks if conscious','Call 108 for severe cases']),
  EmergencyAction(name:'Panic Attack',icon:'😨',category:'Mental',steps:['Move to quiet place','Breathe: inhale 4s, hold 4s, exhale 6s','Use grounding: name 5 things you see','Reassure "this will pass"','Avoid caffeine and stimulants']),
  EmergencyAction(name:'Asthma Attack',icon:'🫁',category:'Airway',steps:['Sit upright, stay calm','Use rescue inhaler (2 puffs)','Wait 1 min, take 2 more puffs if needed','Call 108 if no improvement after 10 min','Loosen tight clothing']),
  EmergencyAction(name:'Diabetic Emergency',icon:'💉',category:'Medical',steps:['Check blood sugar if possible','If low sugar: give juice/glucose tablets','If high sugar: give water, seek help','Do NOT give insulin if unsure','Call 108 if unconscious']),
  EmergencyAction(name:'Eye Injury',icon:'👁️',category:'Trauma',steps:['Do NOT rub the eye','Flush with clean water 15 min for chemicals','Cover with clean cup/shield for objects','Do NOT remove embedded objects','Seek immediate eye care']),
  EmergencyAction(name:'Nosebleed',icon:'👃',category:'Medical',steps:['Sit upright, lean slightly forward','Pinch soft part of nose for 10-15 min','Apply ice to bridge of nose','Do NOT tilt head back','Seek help if bleeding >20 min']),
  EmergencyAction(name:'Fainting',icon:'😵',category:'Medical',steps:['Lay person flat, elevate legs','Loosen tight clothing','Check breathing and pulse','Turn on side if vomiting','Call 108 if not recovering in 1 min']),
  EmergencyAction(name:'Concussion',icon:'🤕',category:'Neurological',steps:['Keep person still and awake','Apply ice to swelling','Monitor for confusion/vomiting','Do NOT give aspirin','Go to ER immediately']),
  EmergencyAction(name:'Spinal Injury',icon:'🔙',category:'Trauma',steps:['Do NOT move the person','Call 108 immediately','Stabilize head and neck','Keep person still','Monitor breathing']),
  EmergencyAction(name:'Carbon Monoxide',icon:'💨',category:'Toxic',steps:['Get to fresh air immediately','Call 108','Open all windows and doors','Do NOT re-enter building','Get oxygen treatment at hospital']),
  EmergencyAction(name:'Chest Pain',icon:'💔',category:'Cardiac',steps:['Call 108 immediately','Chew aspirin if not allergic','Sit upright, stay calm','Loosen clothing','Be ready to perform CPR']),
  EmergencyAction(name:'Dehydration',icon:'💧',category:'Medical',steps:['Drink ORS or water with salt/sugar','Sip slowly, don\'t gulp','Rest in cool area','Avoid caffeine and alcohol','Seek help if confused or not urinating']),
  EmergencyAction(name:'Food Poisoning',icon:'🤮',category:'Toxic',steps:['Stay hydrated with clear fluids','Rest your stomach, eat bland food later','ORS for electrolyte balance','Do NOT take anti-diarrheal initially','See doctor if symptoms >48 hours']),
  EmergencyAction(name:'Hyperventilation',icon:'😤',category:'Airway',steps:['Sit down, try to relax','Breathe into cupped hands','Inhale slowly through nose 4 sec','Exhale through pursed lips 6 sec','Focus on slowing breath rate']),
  EmergencyAction(name:'Jellyfish Sting',icon:'🪼',category:'Bites',steps:['Rinse with vinegar if available','Remove tentacles with tweezers','Soak in hot water (not scalding) 20 min','Take pain medication','Seek help for severe reactions']),
  EmergencyAction(name:'Tick Bite',icon:'🕷️',category:'Bites',steps:['Use fine tweezers to grip tick near skin','Pull straight out steadily','Clean area with antiseptic','Save tick for identification','Watch for rash or fever for 30 days']),
  EmergencyAction(name:'Tooth Knocked Out',icon:'🦷',category:'Dental',steps:['Handle tooth by crown only','Rinse gently, don\'t scrub','Try to place back in socket','If not, store in milk','See dentist within 30 minutes']),
  EmergencyAction(name:'Dislocated Joint',icon:'🦵',category:'Trauma',steps:['Do NOT try to pop it back','Immobilize the joint','Apply ice to reduce swelling','Support with sling or splint','Go to emergency room']),
  EmergencyAction(name:'Severe Headache',icon:'🤯',category:'Neurological',steps:['Rest in dark quiet room','Take paracetamol','Apply cold compress','Stay hydrated','Call 108 if sudden/worst ever headache']),
  EmergencyAction(name:'Insect in Ear',icon:'👂',category:'Medical',steps:['Tilt head, affected ear up','Pour warm olive oil gently','Wait for insect to float out','Do NOT use tweezers','See doctor if not removed']),
  EmergencyAction(name:'Chemical Splash',icon:'⚗️',category:'Toxic',steps:['Remove contaminated clothing','Flush skin with water 20 min','Flush eyes if affected 15 min','Call Poison Control','Do NOT apply creams']),
  EmergencyAction(name:'Near Drowning',icon:'🏊',category:'Airway',steps:['Remove from water','Call 108','Begin CPR if not breathing','Place in recovery position','Keep warm, watch for vomiting']),
  EmergencyAction(name:'Abdominal Pain',icon:'🤢',category:'Medical',steps:['Rest in comfortable position','Apply warm compress','Avoid solid food temporarily','Sip clear fluids','Seek help if severe or with fever']),
  EmergencyAction(name:'Muscle Cramp',icon:'💪',category:'Medical',steps:['Gently stretch the muscle','Massage the area','Apply warm compress','Drink water with electrolytes','Walk gently once eased']),
  EmergencyAction(name:'Sunburn',icon:'☀️',category:'Environmental',steps:['Get out of sun immediately','Cool skin with damp towels','Apply aloe vera gel','Take ibuprofen for pain','Stay hydrated']),
  EmergencyAction(name:'Frostbite',icon:'❄️',category:'Environmental',steps:['Get to warm area','Soak in warm water (40°C/104°F)','Do NOT rub affected area','Do NOT use direct heat','Seek medical attention']),
  EmergencyAction(name:'Panic Disorder',icon:'😰',category:'Mental',steps:['Recognize it\'s a panic attack','Practice 4-7-8 breathing','Ground yourself with 5 senses','Remind: "This is temporary"','Seek therapy for recurring episodes']),
  EmergencyAction(name:'Suicidal Thoughts',icon:'🆘',category:'Mental',steps:['Call helpline: 988 or local crisis line','Stay with the person','Remove harmful objects','Listen without judgment','Get professional help immediately']),
  EmergencyAction(name:'Overdose',icon:'💊',category:'Toxic',steps:['Call 108 immediately','Do NOT induce vomiting','Place in recovery position','Save pill bottles/substances','Monitor breathing, begin CPR if needed']),
  EmergencyAction(name:'Sprains',icon:'🦶',category:'Trauma',steps:['RICE: Rest, Ice, Compression, Elevation','Apply ice 20 min on, 20 min off','Wrap with elastic bandage','Take ibuprofen for pain','See doctor if can\'t bear weight']),
  EmergencyAction(name:'Acid Reflux',icon:'🔥',category:'Medical',steps:['Sit upright, don\'t lie down','Take antacid','Drink small sips of water','Avoid spicy/fatty food','Elevate head when sleeping']),
  EmergencyAction(name:'Migraine',icon:'🌀',category:'Neurological',steps:['Rest in dark, quiet room','Take migraine medication early','Apply cold pack to forehead','Stay hydrated','Avoid known triggers']),
  EmergencyAction(name:'High Blood Pressure',icon:'📈',category:'Cardiac',steps:['Sit down and relax','Practice deep breathing','Take prescribed medication','Avoid salt and caffeine','Call doctor if >180/120']),
  EmergencyAction(name:'Low Blood Sugar',icon:'📉',category:'Medical',steps:['Eat 15g fast-acting sugar','Wait 15 minutes, recheck','Eat a snack with protein','Do NOT skip meals','Seek help if not improving']),
  EmergencyAction(name:'Kidney Stone',icon:'🔶',category:'Medical',steps:['Drink lots of water','Take pain medication','Apply warm compress to back','Strain urine to catch stone','See doctor if fever or blood in urine']),
  EmergencyAction(name:'Appendicitis',icon:'⚠️',category:'Medical',steps:['Call 108 - may need surgery','Do NOT eat or drink','Do NOT take laxatives','Lie still, knees to chest may help','Go to ER immediately']),
  EmergencyAction(name:'Altitude Sickness',icon:'🏔️',category:'Environmental',steps:['Descend to lower altitude','Rest and stay hydrated','Take acetazolamide if available','Avoid alcohol','Seek help if severe headache/confusion']),
  EmergencyAction(name:'Lightning Strike',icon:'⛈️',category:'Environmental',steps:['Call 108 immediately','Check breathing, begin CPR if needed','Treat burns','Move to safe shelter','Monitor for cardiac issues']),
  EmergencyAction(name:'Scorpion Sting',icon:'🦂',category:'Bites',steps:['Clean with soap and water','Apply ice pack','Take pain medication','Keep area still','Seek medical help immediately']),
  EmergencyAction(name:'Spider Bite',icon:'🕸️',category:'Bites',steps:['Clean bite with soap and water','Apply ice','Elevate bitten limb','Take antihistamine','Seek help if severe pain/swelling']),
  EmergencyAction(name:'Vertigo',icon:'🌀',category:'Neurological',steps:['Sit or lie down immediately','Fix eyes on stationary object','Avoid sudden movements','Try Epley maneuver','See doctor if recurring']),
  EmergencyAction(name:'Ear Infection',icon:'👂',category:'Medical',steps:['Apply warm compress','Take pain reliever','Do NOT insert objects','Keep ear dry','See doctor for antibiotics']),
  EmergencyAction(name:'UTI Symptoms',icon:'⚠️',category:'Medical',steps:['Drink plenty of water','Take prescribed antibiotics','Use heating pad for pain','Avoid caffeine/alcohol','See doctor promptly']),
  EmergencyAction(name:'Gallbladder Attack',icon:'😖',category:'Medical',steps:['Avoid fatty foods','Apply warm compress','Take prescribed pain meds','Sit upright','Go to ER if severe']),
  EmergencyAction(name:'Pulled Muscle',icon:'🏋️',category:'Trauma',steps:['Rest the muscle','Ice for 20 min every 2 hours','Gentle stretching after 48 hours','Take anti-inflammatory','See doctor if severe']),
  EmergencyAction(name:'Whiplash',icon:'🚗',category:'Trauma',steps:['Apply ice first 24 hours','Take pain medication','Wear soft collar if prescribed','Gentle neck exercises later','See doctor for assessment']),
  EmergencyAction(name:'Eye Chemical Burn',icon:'🧪',category:'Toxic',steps:['Flush eye with water 15-20 min','Remove contact lenses','Do NOT rub eye','Call Poison Control','Go to ER immediately']),
  EmergencyAction(name:'Ruptured Eardrum',icon:'🔊',category:'Medical',steps:['Keep ear dry','Do NOT insert anything','Take pain relievers','Cover ear loosely','See ENT specialist']),
  EmergencyAction(name:'Severe Diarrhea',icon:'💧',category:'Medical',steps:['Drink ORS solution','Eat BRAT diet','Avoid dairy and spicy food','Rest','See doctor if blood in stool']),
  EmergencyAction(name:'Pneumonia Signs',icon:'🫁',category:'Airway',steps:['Seek medical help promptly','Rest and stay hydrated','Take prescribed antibiotics','Use humidifier','Monitor temperature']),
  EmergencyAction(name:'Meningitis Signs',icon:'🧠',category:'Neurological',steps:['Call 108 IMMEDIATELY','This is life-threatening','Watch for stiff neck + fever + rash','Keep in dark room','Do NOT delay treatment']),
  EmergencyAction(name:'DVT (Blood Clot)',icon:'🦵',category:'Cardiac',steps:['Do NOT massage the leg','Seek medical help immediately','Keep leg elevated','Do NOT walk excessively','Go to ER - can be fatal if clot travels']),
  EmergencyAction(name:'Miscarriage',icon:'🏥',category:'Medical',steps:['Call doctor immediately','Rest, lie down','Save any tissue passed','Go to ER for heavy bleeding','Emotional support is crucial']),
  EmergencyAction(name:'Severe Toothache',icon:'🦷',category:'Dental',steps:['Rinse with warm salt water','Apply clove oil','Take ibuprofen','Cold compress on cheek','See dentist urgently']),
  EmergencyAction(name:'Nose Fracture',icon:'👃',category:'Trauma',steps:['Apply ice immediately','Pinch nose if bleeding','Breathe through mouth','Do NOT try to straighten','See doctor within 24 hours']),
  EmergencyAction(name:'Thumb Dislocation',icon:'👍',category:'Trauma',steps:['Do NOT try to pop it back','Ice and elevate','Splint if possible','Take pain medication','Go to ER']),
  EmergencyAction(name:'Corneal Scratch',icon:'👁️',category:'Medical',steps:['Do NOT rub eye','Blink several times','Flush with clean water','Cover eye loosely','See eye doctor same day']),
  EmergencyAction(name:'Hyperglycemia',icon:'📊',category:'Medical',steps:['Drink water','Take insulin as prescribed','Check ketones','Exercise lightly if safe','Go to ER if vomiting or confused']),
  EmergencyAction(name:'Chest Tightness',icon:'😰',category:'Cardiac',steps:['Sit upright, stay calm','Loosen clothing','Take slow deep breaths','Call 108 if worsening','Could be cardiac or anxiety']),
  EmergencyAction(name:'Wrist Fracture',icon:'✋',category:'Trauma',steps:['Immobilize with splint','Apply ice','Elevate above heart','Take pain medication','Go to ER for X-ray']),
  EmergencyAction(name:'Ankle Sprain',icon:'🦶',category:'Trauma',steps:['RICE: Rest Ice Compression Elevation','Do NOT walk on it','Wrap with elastic bandage','Take ibuprofen','See doctor if can\'t bear weight']),
  EmergencyAction(name:'Rib Fracture',icon:'🩻',category:'Trauma',steps:['Apply ice pack','Take deep breaths despite pain','Sleep propped up','Take pain medication','See doctor - watch for pneumothorax']),
  EmergencyAction(name:'Finger Amputation',icon:'🖐️',category:'Trauma',steps:['Apply pressure to stop bleeding','Wrap amputated part in wet gauze','Place in sealed bag on ice','Do NOT place directly on ice','Rush to ER with the part']),
  EmergencyAction(name:'Jaw Dislocation',icon:'😮',category:'Trauma',steps:['Do NOT force mouth closed','Support jaw with hand','Apply ice','Go to ER immediately','Do NOT try to fix yourself']),
  EmergencyAction(name:'Severe Cramps',icon:'😣',category:'Medical',steps:['Apply heat pad','Gentle stretching','Take ibuprofen','Stay hydrated','See doctor if unusual or severe']),
  EmergencyAction(name:'Rectal Bleeding',icon:'⚠️',category:'Medical',steps:['Note color and amount','Apply gentle pressure','Avoid straining','Drink fluids','See doctor same day']),
  EmergencyAction(name:'Sudden Vision Loss',icon:'👁️',category:'Neurological',steps:['Call 108 - this is emergency','Note which eye and when','Do NOT rub eyes','Sit safely','Could indicate stroke or retinal issue']),
  EmergencyAction(name:'Blood in Urine',icon:'⚠️',category:'Medical',steps:['Drink extra water','Note color and frequency','Avoid aspirin','See doctor urgently','Could be UTI, stones, or other']),
  EmergencyAction(name:'Severe Back Spasm',icon:'🔙',category:'Medical',steps:['Lie on floor with knees bent','Apply ice 20 min','Take muscle relaxant if prescribed','Gentle movement when able','See doctor if numbness']),
  EmergencyAction(name:'Peritonitis Signs',icon:'🚨',category:'Medical',steps:['Call 108 immediately','Do NOT eat or drink','Lie still','This requires emergency surgery','Signs: rigid abdomen, severe pain, fever']),
  EmergencyAction(name:'Testicular Torsion',icon:'🚨',category:'Medical',steps:['Go to ER IMMEDIATELY','Time is critical (6 hour window)','Do NOT delay','Apply ice for pain','Surgery may be needed']),
  EmergencyAction(name:'Ectopic Pregnancy',icon:'🚨',category:'Medical',steps:['Call 108 immediately','Signs: sharp pelvic pain + missed period','Shoulder tip pain is warning sign','This is life-threatening','Do NOT delay treatment']),
  EmergencyAction(name:'Status Epilepticus',icon:'⚡',category:'Neurological',steps:['Call 108 - seizure >5 minutes','Clear dangerous objects','Turn on side','Time the seizure','Do NOT restrain']),
  EmergencyAction(name:'Tension Headache',icon:'😫',category:'Medical',steps:['Take paracetamol or ibuprofen','Apply warm/cold compress','Massage temples gently','Rest in quiet room','Reduce screen time']),
  EmergencyAction(name:'Ingrown Toenail',icon:'🦶',category:'Medical',steps:['Soak foot in warm water','Gently lift nail edge','Place cotton under corner','Apply antiseptic','See podiatrist if infected']),
  EmergencyAction(name:'Hiccups (Severe)',icon:'😯',category:'Medical',steps:['Hold breath 10-20 seconds','Drink ice cold water','Swallow granulated sugar','Breathe into paper bag briefly','See doctor if >48 hours']),
  EmergencyAction(name:'Foreign Body Airway',icon:'🫁',category:'Airway',steps:['Encourage coughing','5 back blows between shoulder blades','5 abdominal thrusts','Alternate back blows and thrusts','Call 108 if object not expelled']),
  EmergencyAction(name:'Anaphylaxis',icon:'🚨',category:'Allergic',steps:['Use EpiPen IMMEDIATELY','Call 108','Lay flat, elevate legs','Second EpiPen dose after 5 min if no improvement','CPR if breathing stops']),
  EmergencyAction(name:'Croup (Child)',icon:'👶',category:'Airway',steps:['Stay calm, comfort child','Steam from hot shower','Cool night air can help','Fluids and rest','Call 108 if struggling to breathe']),
  EmergencyAction(name:'Febrile Seizure',icon:'👶',category:'Neurological',steps:['Place child on side','Clear area of objects','Do NOT put anything in mouth','Cool with lukewarm cloth','Call doctor, 108 if >5 min']),
  EmergencyAction(name:'Playground Fall',icon:'🛝',category:'Trauma',steps:['Check for consciousness','Do NOT move if spine injury suspected','Apply ice to bumps','Watch for vomiting/confusion','ER if loss of consciousness']),
  EmergencyAction(name:'Object in Nose',icon:'👃',category:'Medical',steps:['Do NOT push it further','Try to blow nose gently','Close unaffected nostril','See doctor if not expelled','Do NOT use tweezers']),
  EmergencyAction(name:'Swallowed Object',icon:'😮',category:'Medical',steps:['If breathing normally, see doctor','If choking, do Heimlich maneuver','Do NOT induce vomiting','X-ray may be needed','Most small objects pass naturally']),
  EmergencyAction(name:'Earthquake Injury',icon:'🏚️',category:'Environmental',steps:['Check for injuries','Apply first aid as needed','Cover wounds to prevent infection','Conserve energy if trapped','Signal for help']),
  EmergencyAction(name:'Smoke Inhalation',icon:'💨',category:'Toxic',steps:['Get to fresh air immediately','Call 108','Sit upright to ease breathing','Give oxygen if available','Monitor for delayed symptoms']),
];
